version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: interfaces/api/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - .:/app
    command: uvicorn interfaces.api.main:app --host 0.0.0.0 --port 8000 --reload
