version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: python-ddd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  fastapi:
    build:
      context: .
      dockerfile: interfaces/api/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - .:/app
    command: uvicorn interfaces.api.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  postgres_data:
